### ISSUE TITLE
请问怎样测试？或者使用？

### ISSUE THREAD

**Issue by 1971192997** [blocktree/bitcoin-adapter#2]
reademe 创建的conf是文件还是文件夹？ini文件放到conf文件夹中？

**Comment by Brochao** [comment]
在openwtester目录下创建conf文件夹， 在conf文件夹下创建BTC.ini

**Comment by 1971192997** [comment]
> 在openwtester目录下创建conf文件夹， 在conf文件夹下创建BTC.ini

请问这个适配器最终是怎样用的呢？看了代码基本上是通过test来测试的，但是怎么样运行起来呢？可否给个文档或者教程？
