### ISSUE TITLE
请问这个适配器最终是怎样用的呢？看了代码基本上是通过test来测试的，但是怎么样运行起来呢？可否给个文档或者教程？

### ISSUE THREAD

**Issue by 1971192997** [blocktree/bitcoin-adapter#3]

**Comment by zhiquan911** [comment]
openwallet是一个框架

它提供AssetsAdapter接口，区块链底层开发者实现这个接口，上层应用统一都遵循这个接口进行调用
https://github.com/blocktree/openwallet/blob/master/openwallet/docs/assets.md

目前资料还没完善，基于openwallet框架开发了一个钱包服务平台，提供了go-openw-sdk和go-openw-cli做到了多链钱包的管理，也提供给企业开发者实现资产管理系统。

**Comment by zhiquan911** [comment]
目前第三方开发出的应用还在试验阶段，供内部使用，暂时还没开源。
但基于框架和众多适配器，已经可以开发出一个多链的跨平台钱包系统。
